%% LIRMM : Extract data from txt files generated by Node-RED
%  Autor : Andrea  Sauviat
%  Date  : 04.05.2022

clear all ; % Clear the Workspace
close all ; % Close of the figure
clc       ; % Clear the Command Window


%piroboh282@bodeem.com

%% Download Every .txt Files

% Get info about 'Files_txt' folder
Files_txt_Infos = dir( 'Files_txt' ) ;

% In every SubFolder ...
for Number_Of_SubFolder = 3:1:height(Files_txt_Infos)

    % ... Get the name of the SubFolder, 
    SubFolder_Name = Files_txt_Infos(Number_Of_SubFolder).name ;
    % ... and get info about the content of the SubFolder,
    Files_txt_Release_xx_DDMMYY = dir( strcat('Files_txt/',SubFolder_Name) ) ;

    % ... then get the content of the SubFolder ...
    for Number_Of_SubsubFolder = 3:1:height(Files_txt_Release_xx_DDMMYY)

        % ... Get the name the name of the file .txt
        SubsubFolder_Name = Files_txt_Release_xx_DDMMYY(Number_Of_SubsubFolder).name ;
        % ... Recover the file path
        File_Path = strcat('Files_txt/',SubFolder_Name,'/',SubsubFolder_Name);
        % ... Create a variable name for the downloaded data
        Data_Table_Name = strcat( SubFolder_Name , '_' , SubsubFolder_Name(1:7));
        % ... Asign the data with the variable name just created.
        Data = Convert_File_To_Data_Table( File_Path );
        eval( sprintf('%s = Data',Data_Table_Name) );

    end

end

clc ; % Clear the 'Command Window'

% Delete some values in order to keep the Workspace clean.
clear Files_txt_Infos Number_Of_SubFolder SubFolder_Name ...
      Files_txt_Release_xx_DDMMYY Number_Of_SubsubFolder ...
      SubsubFolder_Name File_Path Data_Table_Name Data

fprintf( " > You have downloaded the following files : \n")
Display_Downloaded_File() ;

fprintf( "\n" ) ;

return

%% Get some information about the LoRa protocole: 

figure("Name","Nombre de gateways LoRa détectées sur la lagune de Bages-Sigean"), 
geoscatter( 0,0,MarkerEdgeColor='#D95319') ; hold on
geoscatter( 0,0,MarkerEdgeColor='#EDB120') ; hold on
geoscatter( 0,0,MarkerEdgeColor='#77AC30') ; hold on
Display_LoRa_Gateways_Data( Release_01_210423_GNAT_03 )
Display_LoRa_Gateways_Data( Release_01_210423_GNAT_04 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_01 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_02 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_03 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_04 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_05 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_06 )
legend("Supérieur ou égal à 3", "Égal à 2", "Égal à 1")




%% 

Display_Lost_LoRa_Data()


%%



%%
clc
Display_Data_Infos()

str = 'exemple';
paddedStr = sprintf('%#*s', 20, str);
disp(paddedStr);

str = 'exemple';
desiredLength = 10;
paddingChar = '-';
numPaddingChars = desiredLength - numel(str);

paddedStr = [str repmat(paddingChar, 1, numPaddingChars)];
disp(paddedStr);

%% 

Get_Nb_Data()

%%

figure("Name","Nombre de gateways LoRa détectées sur la lagune de Bages-Sigean"), 
geoscatter( 0,0,MarkerEdgeColor='#D95319') ; hold on
geoscatter( 0,0,MarkerEdgeColor='#EDB120') ; hold on
geoscatter( 0,0,MarkerEdgeColor='#77AC30') ; hold on
Display_LoRa_Gateways_Data( Release_01_210423_GNAT_03 )
Display_LoRa_Gateways_Data( Release_01_210423_GNAT_04 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_01 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_02 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_03 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_04 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_05 )
Display_LoRa_Gateways_Data( Release_02_260523_GNAT_06 )
legend("Supérieur ou égal à 3", "Égal à 2", "Égal à 1")

%%
clc
Display_LoRa()

%%

Display_LoRa_Gateways_Data( Release_05_210623_GNAT_06 )

%%

Display_LoRa_Gateways_Data( Release_02_260523_GNAT_04 )



%%

function [] = Display_Trajectory_24h_Jellyfish_And_Dummy( Data_Table_Jellyfish , Data_Table_Dummy )

    % Jellyfish
    Display_Trajectory_24h( Data_Table_Jellyfish ) ;

    x_jellyfish = Data_Table_Jellyfish.GPS_Longitude ;
    y_jellyfish = Data_Table_Jellyfish.GPS_Latitude ;
    
    x_jellyfish_smooth = smooth( x_jellyfish , 'rlowess' );
    y_jellyfish_smooth = smooth( y_jellyfish , 'rlowess');
    
    geoplot( y_jellyfish_smooth, x_jellyfish_smooth , 'r',linewidth=2 )

    % Dummy
    Display_Trajectory_24h( Data_Table_Dummy ) ;

    x_dummy = Data_Table_Dummy.GPS_Longitude ;
    y_dummy = Data_Table_Dummy.GPS_Latitude ;
    
    x_dummy_smooth = smooth( x_dummy , 'rlowess' );
    y_dummy_smooth = smooth( y_dummy , 'rlowess');
    
    geoplot( y_dummy_smooth, x_dummy_smooth , 'b',linewidth=2 )

end

function [] = Display_Trajectory_24h_Jellyfish( Data_Table_Jellyfish  )

    % Jellyfish
    Display_Trajectory_24h( Data_Table_Jellyfish ) ;

    x_jellyfish = Data_Table_Jellyfish.GPS_Longitude ;
    y_jellyfish = Data_Table_Jellyfish.GPS_Latitude ;
    
    x_jellyfish_smooth = smooth( x_jellyfish , 'rlowess' );
    y_jellyfish_smooth = smooth( y_jellyfish , 'rlowess');
    
    geoplot( y_jellyfish_smooth, x_jellyfish_smooth , 'r',linewidth=2 )


end


function [Nb_Gateways_EqualTo_1,Nb_Gateways_EqualTo_2,Nb_Gateways_EqualAndOver_3] = Display_Trajectory_24h( Data_Table )

    LoRa_fcnt_Start = Data_Table.LoRa_fcnt( 1 ) ;
    LoRa_fcnt_End   = Data_Table.LoRa_fcnt( height(Data_Table) );

    Nb_fcnt = LoRa_fcnt_End - LoRa_fcnt_Start ;

    %Color = linspace(1,10,height(Data_Table)) / 10

    Color = linspace(1, 10, height(Data_Table));
cmap = colormap;  % Obtenir la colormap par défaut
rgb_values = interp1(linspace(1, 10, size(cmap, 1)), cmap, Color);  % Interpolation des valeurs RVB


    size( Color )
    height(Data_Table) 

    Nb_Gateways_EqualTo_1 = 0 ;
    Nb_Gateways_EqualTo_2 = 0 ;
    Nb_Gateways_EqualAndOver_3 = 0 ;

    for i = 1 : 1 : height(Data_Table) 
        geoscatter( Data_Table.GPS_Latitude(i), Data_Table.GPS_Longitude(i), 'MarkerEdgeColor', rgb_values(i, :)) % Color red
        hold on
    end
    geolimits([43.0146 43.1531],[2.9289 3.1185])

    % fprintf( "Nb Gateways equal to 1 : %d \n", Nb_Gateways_EqualTo_1 ) ;
    % fprintf( "Nb Gateways equal to 2 : %d \n", Nb_Gateways_EqualTo_2 ) ;
    % fprintf( "Nb Gateways equal and over to 3 : %d \n", Nb_Gateways_EqualAndOver_3 ) ;

end





function [] = Display_LoRa()

    figure("Name","Number of LoRa gateways detected. "), 
    geoscatter( 0,0,MarkerEdgeColor='#D95319') ; hold on
    geoscatter( 0,0,MarkerEdgeColor='#EDB120') ; hold on
    geoscatter( 0,0,MarkerEdgeColor='#77AC30') ; hold on

    Nb_Gateways_EqualTo_1 = 0 ;
    Nb_Gateways_EqualTo_2 = 0 ;
    Nb_Gateways_EqualAndOver_3 = 0 ;

    Nb_Messages = 0 ;
    
    % Get info about 'Files_txt' folder
    Files_txt_Infos = dir( 'Files_txt' ) ;
    
    % In every SubFolder ...
    for Number_Of_SubFolder = 3:1:height(Files_txt_Infos)
    
        Files_Number = zeros( 1, 10 ) ; % Set or reset variable
    
        % ... Get the name of the SubFolder, 
        SubFolder_Name = Files_txt_Infos(Number_Of_SubFolder).name ;
        % fprintf( " %s \t|\t " , SubFolder_Name ) ;
        % ... and get info about the content of the SubFolder,
        Files_txt_Release_xx_DDMMYY = dir( strcat('Files_txt/',SubFolder_Name) ) ;
    
        % ... then get the content of the SubFolder ...
        for Number_Of_SubsubFolder = 3:1:height(Files_txt_Release_xx_DDMMYY)
    
            % ... Get the name of the file .txt
            SubsubFolder_Name = Files_txt_Release_xx_DDMMYY(Number_Of_SubsubFolder).name ;
            % .... Find the number the name
            GNAT_xx_String = regexp(SubsubFolder_Name,'\d+','match'); 
            % ... Convert the string to an int
            GNAT_xx_Number = str2double(GNAT_xx_String); 

            % Calculate the Lost LoRa msg
            Data_Table_Name = append(SubFolder_Name, '_' , SubsubFolder_Name);
            Data_Table_Name = Data_Table_Name(1:24) ;
            % string = 'Release_02_260523_GNAT_0' ;
            var_name = sprintf('%s%d',Data_Table_Name, GNAT_xx_Number) ; % Construire le nom de la variable
            array = evalin( 'base' , var_name);          % Obtenir le tableau correspondant à la variable

            % Display a map that show network quality in terms of GPS position.
            [Nb_Gateways_EqualTo_1_fcnt,Nb_Gateways_EqualTo_2_fcnt,Nb_Gateways_EqualAndOver_3_fcnt] = Display_LoRa_Gateways_Data( array ) ;
            Nb_Gateways_EqualTo_1 = Nb_Gateways_EqualTo_1 + Nb_Gateways_EqualTo_1_fcnt ;
            Nb_Gateways_EqualTo_2 = Nb_Gateways_EqualTo_2 + Nb_Gateways_EqualTo_2_fcnt ;
            Nb_Gateways_EqualAndOver_3 = Nb_Gateways_EqualAndOver_3 + Nb_Gateways_EqualAndOver_3_fcnt ;

        end
    
    end

    legend("Equal or over to 3", "Equal to 2", "Equal to 1")

    fprintf( "Nb Gateways equal to 1 : %d \n", Nb_Gateways_EqualTo_1 ) ;
    fprintf( "Nb Gateways equal to 2 : %d \n", Nb_Gateways_EqualTo_2 ) ;
    fprintf( "Nb Gateways equal and over to 3 : %d \n", Nb_Gateways_EqualAndOver_3 ) ;

end

function [] = Get_Nb_Data() 

   fprintf( " Nombre de donnée totale \n");
   Nb_Data = 0 ;

    % Get info about 'Files_txt' folder
    Files_txt_Infos = dir( 'Files_txt' ) ;
    
    % In every SubFolder ...
    for Number_Of_SubFolder = 3:1:height(Files_txt_Infos)
    
        Files_Number = zeros( 1, 10 ) ; % Set or reset variable
    
        % ... Get the name of the SubFolder, 
        SubFolder_Name = Files_txt_Infos(Number_Of_SubFolder).name ;
        % fprintf( " %s \t|\t " , SubFolder_Name ) ;
        % ... and get info about the content of the SubFolder,
        Files_txt_Release_xx_DDMMYY = dir( strcat('Files_txt/',SubFolder_Name) ) ;

        % ... Track of the number of message during the release
        Nb_Data_Release = 0 ;
    
        % ... then get the content of the SubFolder ...
        for Number_Of_SubsubFolder = 3:1:height(Files_txt_Release_xx_DDMMYY)
    
            % ... Get the name of the file .txt
            SubsubFolder_Name = Files_txt_Release_xx_DDMMYY(Number_Of_SubsubFolder).name ;
            % .... Find the number the name
            GNAT_xx_String = regexp(SubsubFolder_Name,'\d+','match'); 
            % ... Convert the string to an int
            GNAT_xx_Number = str2double(GNAT_xx_String); 


            File_Name = append( SubFolder_Name , '_', SubsubFolder_Name ) ;
            File_Name = File_Name(1:(strlength(File_Name)-4));
            fprintf( " %s \t| \t" , File_Name  ) ;

            % Calculate the Lost LoRa msg
            Data_Table_Name = append(SubFolder_Name, '_' , SubsubFolder_Name);
            Data_Table_Name = Data_Table_Name(1:24) ;
            var_name = sprintf('%s%d',Data_Table_Name, GNAT_xx_Number) ; % Construire le nom de la variable
            array = evalin( 'base' , var_name);          % Obtenir le tableau correspondant à la variable

            
            fprintf( " Number of message : %d \n", height(array) ) ; %

            Nb_Data_Release = Nb_Data_Release + height(array) ; % Track number of message during the release
            
            Nb_Data = Nb_Data + height( array ) ; % Track number of message total
    
        end
    
        fprintf(" %s \t\t\t| \t Number of message : %d \n", SubFolder_Name, Nb_Data_Release );
        fprintf("\n");
    
    end

    fprintf( " Total messages : %d \n", Nb_Data );

end

function [] = Display_Data_Infos()

    fprintf( " Fichier .txt \t\t\t\t|\t Nombre de message envoyé \t\t Nb de msg reçu \t\t Pourcentage \t\t Nb de gateways moyen \t\t Nb. de satellite moyen \t\t EHPE Moyen \n");

    % Get info about 'Files_txt' folder
    Files_txt_Infos = dir( 'Files_txt' ) ;
    
    % In every SubFolder ...
    for Number_Of_SubFolder = 3:1:height(Files_txt_Infos)
    
        Files_Number = zeros( 1, 10 ) ; % Set or reset variable
    
        % ... Get the name of the SubFolder, 
        SubFolder_Name = Files_txt_Infos(Number_Of_SubFolder).name ;
        % fprintf( " %s \t|\t " , SubFolder_Name ) ;
        % ... and get info about the content of the SubFolder,
        Files_txt_Release_xx_DDMMYY = dir( strcat('Files_txt/',SubFolder_Name) ) ;
    
        % ... then get the content of the SubFolder ...
        for Number_Of_SubsubFolder = 3:1:height(Files_txt_Release_xx_DDMMYY)
    
            % ... Get the name of the file .txt
            SubsubFolder_Name = Files_txt_Release_xx_DDMMYY(Number_Of_SubsubFolder).name ;
            % .... Find the number the name
            GNAT_xx_String = regexp(SubsubFolder_Name,'\d+','match'); 
            % ... Convert the string to an int
            GNAT_xx_Number = str2double(GNAT_xx_String); 


            File_Name = append( SubFolder_Name , '_', SubsubFolder_Name ) ;
            File_Name = File_Name(1:(strlength(File_Name)-4));
            fprintf( " %s \t| \t" , File_Name  ) ;

            % Calculate the Lost LoRa msg
            Data_Table_Name = append(SubFolder_Name, '_' , SubsubFolder_Name);
            Data_Table_Name = Data_Table_Name(1:24) ;
            var_name = sprintf('%s%d',Data_Table_Name, GNAT_xx_Number) ; % Construire le nom de la variable
            array = evalin( 'base' , var_name);          % Obtenir le tableau correspondant à la variable

            LoRa_fcnt = table2array(array(:, 'LoRa_fcnt'));  % Extraire la colonne 'LoRa_fcnt' comme tableau
            first_value = LoRa_fcnt(1) ;                     % Récupérer la première valeur

            First_Msg = LoRa_fcnt(1) ;
            Last_Msg  = LoRa_fcnt(height(LoRa_fcnt)) ;
            Nb_Msg    = height(LoRa_fcnt) ;
            Msg_Theoretically_Received = Last_Msg - First_Msg + 1 ;

            Msg_Lost = Nb_Msg / Msg_Theoretically_Received ;
            Msg_Lost_Percent = round( Msg_Lost * 100 , 1 ) ;

            % Calcul du nombre de gateways moyen
            LoRa_Gateways = table2array(array(:, 'LoRa_Nb_Gateways')) ;
            LoRa_Gateways_Mean = mean( LoRa_Gateways ) ;

            % Calcul du nombre de satellite moyen
            GPS_Nb_Satellites = table2array(array(:, 'GPS_NbSatellites')) ;
            GPS_Nb_Satellites_Mean = mean( GPS_Nb_Satellites ) ;

            % Calcul du EHPE moyen
            GPS_EHPE = table2array(array(:, 'GPS_EHPE')) ;
            GPS_EHPE_Mean = mean( GPS_EHPE ) ;

            % Affichage des resultats
            fprintf('%d \t', Nb_Msg) ;
            fprintf('%d \t', Msg_Theoretically_Received) ;
            fprintf('%.1f %% \t', Msg_Lost_Percent) ;
            fprintf('%.1f \t', LoRa_Gateways_Mean ) ;
            fprintf('%.1f \t', GPS_Nb_Satellites_Mean ) ;
            fprintf('%.1f \n', GPS_EHPE_Mean ) ;


            % ... Set value to one (presence indicator)
            % Files_Number(1,GNAT_xx_Number) = Msg_Lost_Percent ;

    
        end
    
        % % Display results of wich file are present (1) or not (0)
        % fprintf( '%.1f\t\t ',Files_Number ); 
        fprintf("\n");
    
    end

end


function [] = Display_Lost_LoRa_Data()

    fprintf( " GNAT_xx.txt \t\t|\t 01 \t\t 02 \t\t 03 \t\t 04 \t\t 05 \t\t 06 \t\t 07 \t\t 08 \t\t 09 \t\t 10 \n");
    
    % Get info about 'Files_txt' folder
    Files_txt_Infos = dir( 'Files_txt' ) ;
    
    % In every SubFolder ...
    for Number_Of_SubFolder = 3:1:height(Files_txt_Infos)
    
        Files_Number = zeros( 1, 10 ) ; % Set or reset variable
    
        % ... Get the name of the SubFolder, 
        SubFolder_Name = Files_txt_Infos(Number_Of_SubFolder).name ;
        fprintf( " %s \t|\t " , SubFolder_Name ) ;
        % ... and get info about the content of the SubFolder,
        Files_txt_Release_xx_DDMMYY = dir( strcat('Files_txt/',SubFolder_Name) ) ;
    
        % ... then get the content of the SubFolder ...
        for Number_Of_SubsubFolder = 3:1:height(Files_txt_Release_xx_DDMMYY)
    
            % ... Get the name of the file .txt
            SubsubFolder_Name = Files_txt_Release_xx_DDMMYY(Number_Of_SubsubFolder).name ;
            % .... Find the number the name
            GNAT_xx_String = regexp(SubsubFolder_Name,'\d+','match'); 
            % ... Convert the string to an int
            GNAT_xx_Number = str2double(GNAT_xx_String); 

            % Calculate the Lost LoRa msg
            Data_Table_Name = append(SubFolder_Name, '_' , SubsubFolder_Name);
            Data_Table_Name = Data_Table_Name(1:24) ;
            % string = 'Release_02_260523_GNAT_0' ;
            var_name = sprintf('%s%d',Data_Table_Name, GNAT_xx_Number) ; % Construire le nom de la variable
            array = evalin( 'base' , var_name);          % Obtenir le tableau correspondant à la variable
        
            LoRa_fcnt = table2array(array(:, 'LoRa_fcnt'));  % Extraire la colonne 'LoRa_fcnt' comme tableau
            first_value = LoRa_fcnt(1) ;                     % Récupérer la première valeur
        
            First_Msg = LoRa_fcnt(1) ;
            Last_Msg  = LoRa_fcnt(height(LoRa_fcnt)) ;
            Nb_Msg    = height(LoRa_fcnt) ;
            Msg_Theoretically_Received = Last_Msg - First_Msg + 1 ;
        
            Msg_Lost = Nb_Msg / Msg_Theoretically_Received ;
            Msg_Lost_Percent = round( Msg_Lost * 100 , 1 ) ;
        
            % fprintf('Pourcentage Message LoRa %s : %.1f %%\n', var_name, Msg_Lost_Percent);

            % ... Set value to one (presence indicator)
            Files_Number(1,GNAT_xx_Number) = Msg_Lost_Percent ;

    
        end
    
        % Display results of wich file are present (1) or not (0)
        fprintf( '%.1f\t\t ',Files_Number ); fprintf("\n");
    
    end

end

function [] = Display_Downloaded_File()

    fprintf( " GNAT_xx.txt \t\t|\t 01 \t 02 \t 03 \t 04 \t 05 \t 06 \t 07 \t 08 \t 09 \t 10 \n");
    
    % Get info about 'Files_txt' folder
    Files_txt_Infos = dir( 'Files_txt' ) ;
    
    % In every SubFolder ...
    for Number_Of_SubFolder = 3:1:height(Files_txt_Infos)
    
        Files_Number = zeros( 1, 10 ) ; % Set or reset variable
    
        % ... Get the name of the SubFolder, 
        SubFolder_Name = Files_txt_Infos(Number_Of_SubFolder).name ;
        fprintf( " %s \t|\t " , SubFolder_Name ) ;
        % ... and get info about the content of the SubFolder,
        Files_txt_Release_xx_DDMMYY = dir( strcat('Files_txt/',SubFolder_Name) ) ;
    
        % ... then get the content of the SubFolder ...
        for Number_Of_SubsubFolder = 3:1:height(Files_txt_Release_xx_DDMMYY)
    
            % ... Get the name of the file .txt
            SubsubFolder_Name = Files_txt_Release_xx_DDMMYY(Number_Of_SubsubFolder).name ;
            % .... Find the number the name
            GNAT_xx_String = regexp(SubsubFolder_Name,'\d+','match'); 
            % ... Convert the string into a string
            GNAT_xx_Number = str2double(GNAT_xx_String); 
            % ... Set value to one (presence indicator)
            Files_Number(1,GNAT_xx_Number) = 1 ;
    
        end
    
        % Display results of wich file are present (1) or not (0)
        fprintf( ' %d\t\t ',Files_Number ); fprintf("\n");
    
    end

end


function [ Data_Table_With_Variables_Name ] = Convert_File_To_Data_Table( Path_Of_The_File )
    Data_Table_Without_Variables_Name = readtable( Path_Of_The_File );
    Data_Table_With_Variables_Name = Set_Variables_Names_To_Data_Table( Data_Table_Without_Variables_Name );
end


function [ Data_Table_With_Variables_Name ] = Set_Variables_Names_To_Data_Table( Data_Table_Without_Variables_Name )

    Default_Variables_Names = [ "Var1" ,"Var2" ,"Var3" ,"Var4" ,"Var5" ,"Var6" ,"Var7" ,"Var8" ,"Var9" ,"Var10", ...
                                "Var11","Var12","Var13","Var14","Var15","Var16","Var17","Var18","Var19","Var20", ...
                                "Var21","Var22","Var23","Var24","Var25","Var26","Var27","Var28","Var29","Var30", ...
                                "Var31" ] ;

    Custom_Varialbes_Names = [ "Board_Name", "Battery_Level", "Time_User", "Time_PreviousMsg", "Time_Elapsed", "time", "STM32_Temperature", ...
                               "LoRa_DevEUI", "LoRa_Network_Quality", "LoRa_RSSI", "LoRa_SNR", "LoRa_ESP", "LoRa_SF", "LoRa_Frequency", "LoRa_Nb_Gateways", "LoRa_fcnt", "LoRa_Payload", ...
                               "GPS_Latitude", "GPS_Longitude", "GPS_NbSatellites", "GPS_EHPE", "GPS_Distance", "GPS_Vitesse", "GPS_Direction", ...
                               "Acc_Temp", "Acc_AxeX", "Acc_AxeY", "Acc_AxeZ", "Acc_Roll", "Acc_Pitch", "Acc_Yaw"] ;
    
    Data_Table_With_Variables_Name = renamevars( Data_Table_Without_Variables_Name , ...
                                                 Default_Variables_Names, ...
                                                 Custom_Varialbes_Names );
end


function [Nb_Gateways_EqualTo_1,Nb_Gateways_EqualTo_2,Nb_Gateways_EqualAndOver_3] = Display_LoRa_Gateways_Data( Data_Table )

    Nb_Gateways_EqualTo_1 = 0 ;
    Nb_Gateways_EqualTo_2 = 0 ;
    Nb_Gateways_EqualAndOver_3 = 0 ;

    for i = 1 : 1 : height(Data_Table) 

        if( Data_Table.GPS_EHPE <= 50 )
        if( Data_Table.LoRa_Nb_Gateways(i)==1 )
            Nb_Gateways_EqualTo_1 = Nb_Gateways_EqualTo_1 + 1 ;
            geoscatter( Data_Table.GPS_Latitude(i), Data_Table.GPS_Longitude(i), MarkerEdgeColor='#D95319' ) % Color red
        end
        if( Data_Table.LoRa_Nb_Gateways(i)==2 )
            Nb_Gateways_EqualTo_2 = Nb_Gateways_EqualTo_2 + 1 ;
            geoscatter( Data_Table.GPS_Latitude(i), Data_Table.GPS_Longitude(i), MarkerEdgeColor='#EDB120' ) % Color yellow
        end
        if( Data_Table.LoRa_Nb_Gateways(i)>=3 )
            Nb_Gateways_EqualAndOver_3 = Nb_Gateways_EqualAndOver_3 + 1 ;
            geoscatter( Data_Table.GPS_Latitude(i), Data_Table.GPS_Longitude(i), MarkerEdgeColor='#77AC30' ) % Color green
        end
        hold on
        end

    end
    geolimits([43.0146 43.1531],[2.9289 3.1185])

    % fprintf( "Nb Gateways equal to 1 : %d \n", Nb_Gateways_EqualTo_1 ) ;
    % fprintf( "Nb Gateways equal to 2 : %d \n", Nb_Gateways_EqualTo_2 ) ;
    % fprintf( "Nb Gateways equal and over to 3 : %d \n", Nb_Gateways_EqualAndOver_3 ) ;

end









